"""
OGB — OrbitalGuard
Pydantic models for vision detection pipeline responses.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class BoundingBox(BaseModel):
    """Normalised bounding box [0, 1] in YOLO format."""
    x_center: float = Field(..., ge=0.0, le=1.0)
    y_center: float = Field(..., ge=0.0, le=1.0)
    width: float = Field(..., ge=0.0, le=1.0)
    height: float = Field(..., ge=0.0, le=1.0)


class Detection(BaseModel):
    """Single object detected by YOLOv8n."""
    class_id: int = Field(..., ge=0)
    class_name: str
    confidence: float = Field(..., ge=0.0, le=1.0)
    bounding_box: BoundingBox
    # Pixel-space box for front-end rendering (set by inference service)
    x1_px: Optional[int] = None
    y1_px: Optional[int] = None
    x2_px: Optional[int] = None
    y2_px: Optional[int] = None


class DetectionResponse(BaseModel):
    model_config = ConfigDict(protected_namespaces=())
    """
    Response returned by POST /api/v1/detect.

    Vision system output only: class + confidence + bounding box.
    This does NOT include orbital data, distance, velocity, or any
    collision probability — those come from the orbital pipeline only.
    """
    image_width: int
    image_height: int
    detections: List[Detection] = []
    detection_count: int = 0
    model_version: str = "ogb_yolov8n_v1"
    inference_latency_ms: Optional[float] = None
    # Plain-English summary for the copilot context (generated by service)
    summary: Optional[str] = None
    # Enriched structured context for the AI copilot (computed deterministically)
    copilot_context: Optional[Dict[str, Any]] = None
