/**
 * OGB — OrbitalGuard
 * ExportButton — Feature #4: Export detection report as JSON or PDF.
 *
 * JSON export: straightforward serialisation of current detection + history.
 * PDF export:  client-side jsPDF one-pager — image thumbnail, detection list,
 *              timestamp, model version, safety disclaimer.
 */
"use client";

import { useState } from "react";
import { Download, FileText, Loader } from "lucide-react";
import type { Detection, DetectionResponse, DetectionHistoryEntry } from "@/lib/types";

interface Props {
  result: DetectionResponse;
  filteredDetections: Detection[];
  imageSrc: string | null;
  detectionHistory: DetectionHistoryEntry[];
}

const SAFETY_DISCLAIMER =
  "DECISION-SUPPORT TOOL OUTPUT — This report is generated by OGB (OrbitalGuard) v0.1.0. " +
  "All detection results are produced by a YOLOv8n computer-vision model and are provided " +
  "for situational-awareness support only. This output does NOT constitute an autonomous " +
  "determination, collision probability, or manoeuvre recommendation. " +
  "The human operator retains full responsibility for all decisions. " +
  "Do not act on this report without independent verification.";

export default function ExportButton({
  result,
  filteredDetections,
  imageSrc,
  detectionHistory,
}: Props) {
  const [pdfLoading, setPdfLoading] = useState(false);

  // ── JSON export ──────────────────────────────────────────────────────────

  function exportJSON() {
    const payload = {
      export_meta: {
        generated_at: new Date().toISOString(),
        tool: "OGB OrbitalGuard v0.1.0",
        safety_disclaimer: SAFETY_DISCLAIMER,
      },
      current_detection: result,
      filtered_detections: filteredDetections,
      session_history_summary: detectionHistory.map((entry) => ({
        timestamp: entry.timestamp,
        detection_count: entry.result.detection_count,
        classes_detected: [...new Set(entry.result.detections.map((d) => d.class_name))],
        model_version: entry.result.model_version,
      })),
    };

    const blob = new Blob([JSON.stringify(payload, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `ogb_detection_${new Date().toISOString().replace(/[:.]/g, "-")}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  // ── PDF export ───────────────────────────────────────────────────────────

  async function exportPDF() {
    setPdfLoading(true);
    try {
      // Dynamic import — keeps jsPDF out of the initial bundle
      const { jsPDF } = await import("jspdf");

      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageW = doc.internal.pageSize.getWidth();
      const pageH = doc.internal.pageSize.getHeight();
      const margin = 15;
      const contentW = pageW - margin * 2;
      let y = margin;

      // ── Helpers ──────────────────────────────────────────────────────────
      const heading = (text: string, size = 13) => {
        doc.setFontSize(size);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30, 35, 55);
        doc.text(text, margin, y);
        y += size * 0.6;
      };

      const label = (text: string, size = 8) => {
        doc.setFontSize(size);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(90, 100, 120);
        doc.text(text, margin, y);
        y += size * 0.52;
      };

      const body = (text: string, size = 9, indent = 0) => {
        doc.setFontSize(size);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(30, 40, 60);
        const lines = doc.splitTextToSize(text, contentW - indent);
        doc.text(lines, margin + indent, y);
        y += lines.length * size * 0.42 + 1;
      };

      const divider = () => {
        doc.setDrawColor(200, 210, 230);
        doc.setLineWidth(0.3);
        doc.line(margin, y, pageW - margin, y);
        y += 4;
      };

      const gap = (mm = 3) => { y += mm; };

      // ── Header ───────────────────────────────────────────────────────────
      doc.setFillColor(6, 13, 24);
      doc.rect(0, 0, pageW, 20, "F");
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(226, 232, 240);
      doc.text("OGB OrbitalGuard — Detection Report", margin, 13);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(160, 174, 192);
      doc.text("Decision-support only · Operator makes all decisions", pageW - margin, 13, { align: "right" });
      y = 26;

      // ── Report metadata ───────────────────────────────────────────────────
      heading("Report Metadata", 11);
      gap(1);
      label(`Generated:      ${new Date().toISOString()}`);
      label(`Model version:  ${result.model_version}`);
      label(`Image size:     ${result.image_width} × ${result.image_height} px`);
      if (result.inference_latency_ms != null) {
        label(`Inference time: ${result.inference_latency_ms.toFixed(1)} ms`);
      }
      label(`Total returned: ${result.detection_count} detection${result.detection_count !== 1 ? "s" : ""} (backend threshold ≥ 25%)`);
      label(`Report shows:   ${filteredDetections.length} detection${filteredDetections.length !== 1 ? "s" : ""} (after client-side filter)`);
      gap(2);
      divider();

      // ── Thumbnail ─────────────────────────────────────────────────────────
      if (imageSrc) {
        try {
          // Load image as data URL for jsPDF
          const imgDataUrl = await loadImageAsDataUrl(imageSrc);
          const maxThumbW = contentW * 0.45;
          const maxThumbH = 55;
          // Calculate fitted dimensions maintaining aspect ratio
          const rawW = result.image_width || 640;
          const rawH = result.image_height || 640;
          const ratio = Math.min(maxThumbW / rawW, maxThumbH / rawH);
          const thumbW = rawW * ratio;
          const thumbH = rawH * ratio;
          doc.addImage(imgDataUrl, "JPEG", margin, y, thumbW, thumbH);

          // Detection summary beside the thumbnail
          const textX = margin + thumbW + 6;
          const textW2 = pageW - margin - textX;
          doc.setFontSize(9);
          doc.setFont("helvetica", "bold");
          doc.setTextColor(59, 130, 246);
          doc.text(`${filteredDetections.length}`, textX, y + 8);
          doc.setFontSize(8);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(90, 100, 120);
          doc.text("objects detected", textX, y + 13);

          const uniqueClasses = [...new Set(filteredDetections.map((d) => d.class_name))];
          let ty = y + 20;
          for (const cls of uniqueClasses.slice(0, 6)) {
            const count = filteredDetections.filter((d) => d.class_name === cls).length;
            doc.setFontSize(7.5);
            doc.setFont("helvetica", "normal");
            doc.setTextColor(60, 70, 90);
            doc.text(`• ${cls} (×${count})`, textX, ty);
            ty += 5;
          }

          y += thumbH + 4;
        } catch {
          // If thumbnail fails, just continue without it
          gap(2);
        }
      }
      divider();

      // ── Detection table ───────────────────────────────────────────────────
      heading("Detections", 11);
      gap(1);

      if (filteredDetections.length === 0) {
        body("No detections above the current confidence threshold.");
      } else {
        // Table header
        const cols = { idx: margin, cls: margin + 7, conf: margin + 60, bbox: margin + 85 };
        doc.setFontSize(7.5);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(90, 100, 120);
        doc.text("#", cols.idx, y);
        doc.text("Class", cols.cls, y);
        doc.text("Conf.", cols.conf, y);
        doc.text("Bbox (x1,y1,x2,y2 px)", cols.bbox, y);
        y += 4;
        doc.setDrawColor(200, 210, 230);
        doc.setLineWidth(0.2);
        doc.line(margin, y, pageW - margin, y);
        y += 3;

        for (let i = 0; i < filteredDetections.length; i++) {
          const d = filteredDetections[i];
          // Check if we need a new page
          if (y > pageH - 30) {
            doc.addPage();
            y = margin;
          }
          doc.setFontSize(7.5);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(30, 40, 60);
          doc.text(`${i + 1}`, cols.idx, y);
          doc.text(d.class_name, cols.cls, y);
          const confPct = `${(d.confidence * 100).toFixed(1)}%`;
          // Colour-code confidence
          if (d.confidence >= 0.75) doc.setTextColor(22, 163, 74);
          else if (d.confidence >= 0.50) doc.setTextColor(202, 138, 4);
          else doc.setTextColor(234, 88, 12);
          doc.text(confPct, cols.conf, y);
          doc.setTextColor(30, 40, 60);
          const bboxStr = `(${d.x1_px ?? "?"}, ${d.y1_px ?? "?"}, ${d.x2_px ?? "?"}, ${d.y2_px ?? "?"})`;
          doc.text(bboxStr, cols.bbox, y);
          y += 5;
          // Alternating row background
          if (i % 2 === 0) {
            doc.setFillColor(245, 247, 252);
            doc.rect(margin, y - 4.5, contentW, 5, "F");
          }
        }
      }
      gap(3);
      divider();

      // ── Session history summary ───────────────────────────────────────────
      if (detectionHistory.length > 0) {
        heading("Session History Summary", 11);
        gap(1);
        label(`${detectionHistory.length} detection run${detectionHistory.length !== 1 ? "s" : ""} this session:`);
        gap(1);
        for (let i = 0; i < detectionHistory.length; i++) {
          const entry = detectionHistory[i];
          const classes = [...new Set(entry.result.detections.map((d) => d.class_name))].join(", ") || "none";
          const t = new Date(entry.timestamp).toLocaleTimeString();
          body(`#${i + 1} · ${t} — ${entry.result.detection_count} detection${entry.result.detection_count !== 1 ? "s" : ""}: ${classes}`, 8, 3);
        }
        gap(3);
        divider();
      }

      // ── Safety disclaimer ─────────────────────────────────────────────────
      // Always on the last section, may push to a new page
      if (y > pageH - 35) {
        doc.addPage();
        y = margin;
      }
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "bolditalic");
      doc.setTextColor(100, 110, 130);
      doc.text("SAFETY DISCLAIMER", margin, y);
      y += 4;
      doc.setFont("helvetica", "italic");
      doc.setTextColor(110, 120, 140);
      const disclaimerLines = doc.splitTextToSize(SAFETY_DISCLAIMER, contentW);
      doc.text(disclaimerLines, margin, y);
      y += disclaimerLines.length * 3.5 + 4;

      // ── Footer on every page ──────────────────────────────────────────────
      const totalPages = (doc.internal as { getNumberOfPages(): number }).getNumberOfPages();
      for (let pg = 1; pg <= totalPages; pg++) {
        doc.setPage(pg);
        doc.setFillColor(6, 13, 24);
        doc.rect(0, pageH - 10, pageW, 10, "F");
        doc.setFontSize(6.5);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(74, 85, 104);
        doc.text(
          `OGB OrbitalGuard · Decision-support only · Page ${pg}/${totalPages}`,
          pageW / 2,
          pageH - 4,
          { align: "center" }
        );
      }

      doc.save(`ogb_detection_${new Date().toISOString().replace(/[:.]/g, "-")}.pdf`);
    } catch (err) {
      console.error("PDF export failed:", err);
      alert("PDF export failed. Please try the JSON export instead.");
    } finally {
      setPdfLoading(false);
    }
  }

  return (
    <div className="rounded border border-[#2d3748] bg-[#0d1117] overflow-hidden">
      <div className="px-4 py-2 bg-[#161b27] border-b border-[#2d3748]">
        <span className="text-[#4a5568] text-xs font-mono uppercase tracking-widest">
          Export Report
        </span>
      </div>
      <div className="flex items-center gap-2 px-4 py-3">
        <button
          onClick={exportJSON}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded border border-[#2d3748] bg-[#0f1624] text-xs font-mono text-[#a0aec0] hover:border-[#3b82f6] hover:text-[#7aa2d4] transition-colors"
          title="Export full detection data as JSON"
        >
          <Download size={12} strokeWidth={1.5} />
          JSON
        </button>
        <button
          onClick={exportPDF}
          disabled={pdfLoading}
          className={[
            "flex items-center gap-1.5 px-3 py-1.5 rounded border text-xs font-mono transition-colors",
            pdfLoading
              ? "border-[#2d3748] text-[#4a5568] cursor-not-allowed"
              : "border-[#2d3748] bg-[#0f1624] text-[#a0aec0] hover:border-[#3b82f6] hover:text-[#7aa2d4]",
          ].join(" ")}
          title="Export one-page summary as PDF"
        >
          {pdfLoading ? (
            <Loader size={12} className="animate-spin" strokeWidth={1.5} />
          ) : (
            <FileText size={12} strokeWidth={1.5} />
          )}
          {pdfLoading ? "Generating…" : "PDF"}
        </button>
        <span className="text-[#2d3748] text-[10px] font-mono ml-1">
          Decision-support only
        </span>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Helper: load an object URL / data URL as a data URL for jsPDF
// ---------------------------------------------------------------------------

function loadImageAsDataUrl(src: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const img = new window.Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      const ctx = canvas.getContext("2d")!;
      ctx.drawImage(img, 0, 0);
      resolve(canvas.toDataURL("image/jpeg", 0.85));
    };
    img.onerror = reject;
    img.src = src;
  });
}
